name: Quality Tools
on: [push, pull_request]

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  quality_tools:
    name: Quality Tools
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
        -   name: Checkout
            uses: actions/checkout@v3
        -   name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: '8.2'
                tools: squizlabs/php_codesniffer:3, pint:1
        -   name: Composer Install
            run: composer install --classmap-authoritative --no-interaction --no-cache
        -   name: PHP_CodeSniffer
            run: phpcs --standard=build/php_codesniffer.xml
        -   name: PHP Pint
            run: pint --config=build/pint.json
