name: Quality Tools
on: [push, pull_request]

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
        name: Quality Tools
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    tools: squizlabs/php_codesniffer:3, friendsofphp/php-cs-fixer:3
            -   name: Composer Install
                run: composer install --classmap-authoritative --no-interaction --no-cache
            -   name: PHP_CodeSniffer
                run: phpcs --standard=build/php_codesniffer.xml
            -   name: PHP CS Fixer
                run: php-cs-fixer fix --config=build/php-cs-fixer.php --diff --dry-run --using-cache=no
